# simulator_config.yaml
simulator:
  # 渲染策略配置
  render_strategies:
    difix_trt:
      enabled: true
      conditions:
        - env: USE_DIFIX_TENSORRT
          value: "true"
      strategy_class: "DifixRenderStrategy"

    difix:
      enabled: true
      conditions:
        - env: USE_DIFIX
          value: "true"
        - env: USE_DIFIX_LORA  
          value: "true"
        - env: USE_DIFIX_FINETUNED
          value: "true"  
        - env: USE_DIFIX_REFERENCE
          value: "true"
      strategy_class: "DifixCarmaskAwareRenderStrategy" # strategy_class: "DifixRenderStrategy"

    original_png:
      enabled: true
      conditions:
        - env: RENDER_ORIGINAL_PNG
          value: "true"
      strategy_class: "OriginalPngRenderStrategy"
      
    default:
      enabled: true
      conditions:
        - always: true
      strategy_class: "DefaultRenderStrategy"

  # 渲染模型配置
  models:
    difix:
      # 基础配置
      base:
        enabled: true
        conditions:
          - env: USE_DIFIX
            value: "true"
        config:
          cam: [0, 2, 3, 4, 5, 6, 7]
          compile_pipeline: false
          fp16: true
          guidance_scale: 3.0
          pretrained_path: "/workspace/group_share/adc-sim/users/led/ckpts/difix_origin"
          prompt: "remove degradation"
          scale: 1
          timesteps: [199]
          use_reference_image: false
          xformers: true
      
      # 扩展
      variants:
        lora:
          enabled: true
          conditions:
            - env: USE_DIFIX_LORA
              value: "true"
          config_overrides:
            lora_ckpt_path: "{CKPT:/workspace/group_share/adc-sim/users/cloudsim/difix/ckpt_v2/{SCENE_IDX:default}}"
            
        finetuned:
          enabled: true
          conditions:
            - env: USE_DIFIX_FINETUNED
              value: "true"
          config_overrides:
            lora_ckpt_path: "{CKPT:/workspace/group_share/adc-sim/users/cloudsim/difix/ckpt_finetuned/default}"
            reference_image_path: "{REF_PATH:/workspace/group_share/adc-sim/users/cloudsim/images_origin/{SCENE_IDX}/images_origin/}"
        reference_image:
          enabled: true
          conditions:
            - env: USE_DIFIX_REFERENCE
              value: "true"
          config_overrides:
            use_reference_image: True
            pretrained_path: "/workspace/group_share/adc-sim/users/led/ckpts/difix_ref_mask"
            reference_image_path: "{REF_PATH:/workspace/group_share/adc-sim/users/cloudsim/images_origin/{SCENE_IDX}/images_origin/}"
            lora_ckpt_path: "{CKPT:/workspace/group_share/adc-sim/users/cloudsim/difix/ckpt_finetuned/default_ref}"
        tensor_rt:
          enabled: true
          conditions:
            - env: USE_DIFIX_TENSORRT
              value: "true"
          config_overrides:
            use_tensorrt: True
            use_reference_image: True
            pretrained_path: "/workspace/group_share/adc-sim/users/led/ckpts/difix_ref"
            reference_image_path: "{REF_PATH:/workspace/group_share/adc-sim/users/cloudsim/images_origin/{SCENE_IDX}/images_origin/}"
            lora_ckpt_path: "{CKPT:/workspace/group_share/adc-sim/users/cloudsim/difix/ckpt_finetuned/default_trt}"