# [vehicle][camera][position]: x y z in rig coor, value in design;
# [vehicle][camera][angle]: pitch yaw roll, value in design;
# [vehicle][camera][tolerance] pitch_range yaw_range roll_range, represent the allowable range of calibration results(angle +/- angele_range);


vehicle:
  -
    vehicle_name: e38
    wheelbase: 2999
    camera:
      -
        name: front_fisheye
        position: [1912.87, 4.22, 1494.00]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [1910.25, -45.78, 1493.20]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2142.09, 935.85, 1091.70]
        angle: [0.0, -39.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2142.09, -935.85, 1091.70]
        angle: [0.0, -139.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2409.71, 938.79, 1021.62]
        angle: [0.0, 43.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2409.71, -938.79, 1021.62]
        angle: [0.0, 137.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-1010.92, 0, 624.97]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: e28a
    wheelbase: 2999
    camera:
      -
        name: front_fisheye
        position: [1775.25, 4.22, 1303.36]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [1772.64, -45.78, 1302.55]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2115.87, 893.04, 911.46]
        angle: [0.0, -40.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2115.87, -893.04, 911.46]
        angle: [0.0, -140.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2395.31, 921.89, 742.29]
        angle: [0.0, 43.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2395.31, -921.89, 742.29]
        angle: [0.0, 137.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-963.76, 57.73, 513.03]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: f30
    wheelbase: 2870
    camera:
      -
        name: front_fisheye
        position: [1970.75, 0.0, 1474.66]
        angle: [-0.8, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [1968.14, -50.0, 1473.86]
        angle: [-0.6, -89.5, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2538.89, 933.29, 906.46]
        angle: [0.0, -40.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2538.89, -933.29, 906.46]
        angle: [0.0, -140.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2434.25, 927.21, 911.3]
        angle: [1.0, 42.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2434.25, -927.21, 911.3]
        angle: [0.0, 137.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-904.0, 0.0, 1118.2]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: h93
    wheelbase: 3160
    camera:
      -
        name: front_fisheye
        position: [2490.13, 0.03, 1535.95]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [2487.52, -49.96, 1535.15]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2540.68, 940.498, 1182.41]
        angle: [0.0, -40.0, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2540.684, -940.498, 1182.41]
        angle: [0.0, -140.0, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2715.77, 976.77, 976.86]
        angle: [0.0, 43.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2715.77, -976.77, 976.86]
        angle: [0.0, 137.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-1122.60, 0.0, 552.35]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: f57
    wheelbase: 2999
    camera:
      -
        name: front_fisheye
        position: [2020.28, 0, 1333.90]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [2017.66, -50, 1333.103]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2275.25, 921.6, 924.5]
        angle: [0.0, -40.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2275.25, -921.6, 924.5]
        angle: [0.0, -140.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2550.22, 948.66, 799.84]
        angle: [0.0, 43.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2550.22, -948.66, 799.84]
        angle: [0.0, 137.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-1062.77, 69.27, 978]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: f01
    wheelbase: 2870
    camera:
      -
        name: front_fisheye
        position: [1970.75, 0.0, 1474.66]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [1968.14, -50.0, 1473.86]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2273.53, 895.15, 1070.98]
        angle: [0.0, -40.0, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2273.53, -895.15, 1070.98]
        angle: [0.0, -140.0, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2435, 937, 909]
        angle: [1.0, 42.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2435, -937, 909]
        angle: [0.0, 137.0, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-1004.0, 35, 994]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: e38b
    wheelbase: 2990
    camera:
      -
        name: front_fisheye
        position: [1912.87, 4.22, 1494.00]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [1910.25, -45.78, 1493.20]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2142.09, 935.85, 1091.70]
        angle: [0.0, -39.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2142.09, -935.85, 1091.70]
        angle: [0.0, -139.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2409.71, 938.79, 1021.62]
        angle: [0.0, 43.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2409.71, -938.79, 1021.62]
        angle: [0.0, 137.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-1010.92, 0.0, 624.97]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: e29
    wheelbase: 2999
    camera:
      -
        name: front_fisheye
        position: [1872.918, -4, 1289.722]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [1870.302, -54, 1288.922]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2131.254, 943.705, 941.503]
        angle: [0.0, -39.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2131.254, -943.705, 941.503]
        angle: [0.0, -139.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2452.038, 973.655, 721.4]
        angle: [0.0, 43.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2452.038, -973.655, 721.4]
        angle: [0.0, 137.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-1076.269, 69.269, 870.027]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]

  -
    vehicle_name: d01m
    wheelbase: 2999
    camera:
      -
        name: front_fisheye
        position: [1838.129, 0.0, 1290.008]
        angle: [0.0, -90.0, -82.8]
        tolerance: [2.5, 3.0, 1.5]
      -
        name: front_narrow
        position: [1835.512, -50.0, 1289.208]
        angle: [0.0, -90.0, -90.0]
        tolerance: [2.5, 2.5, 1.5]
      -
        name: side_front_left
        position: [2111.014, 930.756, 930.695]
        angle: [0.0, -39.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_front_right
        position: [2111.014, -930.756, 930.695]
        angle: [0.0, -139.5, -94.4]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_left
        position: [2419.517, 936.299, 738.535]
        angle: [0.0, 43.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: side_rear_right
        position: [2419.517, -936.299, 738.535]
        angle: [0.0, 137.5, -90.0]
        tolerance: [3.0, 3.0, 3.0]
      -
        name: rear_main
        position: [-947.07, 55.976, 534.257]
        angle: [0.0, 90.0, -90.0]
        tolerance: [3.0, 3.0, 4.0]