seed: 17
device: "cuda:0"
output: "placeholder for local, should updated dynamic when run"

dataset:
  dataset: "XpengDataset"
  clip_path: "placeholder for local, should updated dynamic when run"
  replace_name: False
  clip_list:
    - "placeholder for local, should updated dynamic when run"

  min_distance: 0.2

  # resized image size
  image_width: 968
  image_height: 774

  camera_names:
    - cam0
    - cam2
    - cam3
    - cam4
    - cam5
    - cam6
    - cam7

train:
  vis: False
  debug_from: -1
  detect_anomaly: False
  start_checkpoint: ""
  eval: True
  save: True
  add_triangle_centroid: False

model:
  bev_resolution: 0.06 # meters
  cut_range: 10
  extend_from_last_frame: 30
  sh_degree: 1
  use_rgb: True
  use_label: True
  opt_xy: False
  white_background: False
  use_exposure: False

optimization:
  epochs: 2
  random_background: False
  position_lr_init: 0.000016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 4000
  percent_dense: 0.01
  feature_lr: 0.0005
  opacity_lr: 0.0001
  scaling_lr: 0.0001
  rotation_lr: 0.0001
  rgb_lr: 0.008
  label_lr: 0.1
  exposure_lr: 0.001

  seg_loss_weight: 0.06
  smooth_loss_weight: 0.003  # 1 if z_weight > 0
  depth_loss_weight: 0
  z_weight: 0  # 0.02 if supervise z
  z_xy_distance_threshold: 0.2  # meters; <=0 disables z loss gating

pipeline:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False

affine:
  params:
    embedding_dim: 4
    base_mlp_layer_width: 64
    pixel_affine: False
    use_random_init: True
    use_camera_embedding: False
  optim:
    all:
      lr: 5.0e-4
      lr_final: 1.0e-4
      warmup_steps: 1000
      max_steps: 10000
      lr_pre_warmup: 1.0e-7
      ramp: cosine
      weight_decay: 1.0e-6
  loss_weight: 1.0e-5
