!!python/object:mvsnet.mvsa.src.mvsanywhere.options.Options
name: mvsanywhere
output_base_path: /workspace/group_share/adc-sim/users/zf/vision_exp/lidar/c-43df1bb8-eb78-37af-b4fa-1e0c71f339ad/vision/recon/mvsnet_output
load_weights_from_checkpoint: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models/mvsanywhere_hero.ckpt
scan_parent_directory: /workspace/group_share/adc-sim/users/zf/vision_exp/lidar/c-43df1bb8-eb78-37af-b4fa-1e0c71f339ad/vision/recon/mvsnet_metadata
scan_name: xpeng
num_workers: 8
batch_size: 1
run_fusion: true
compute_metrics: false
depth_fuser: custom_open3d
fuse_color: true
fusion_max_depth: 50.0
fusion_resolution: 0.1
extended_neg_truncation: true
dump_depth_visualization: true
dump_seg_mask_visualization: false
filter_cam_ids: "2,3,4,5,6,7"
fusion_apply_downsampling: true
fusion_voxel_size: 0.05
fusion_apply_stat_filter: true
fusion_stat_nb_neighbors: 40
fusion_stat_std_ratio: 2.0
fusion_apply_cluster_filter: true
fusion_cluster_eps: 0.5
fusion_cluster_min_points: 10
fusion_dbscan_voxel_size: 0.1
fusion_enable_geometric_consistency: true
fusion_enable_cross_camera: true
fusion_thres_view: 3
fusion_type: pointcloud
save_frame_infos: false