seed: 6666
debug_mode: False
# ------------- Dataset ------------ #
data:
  type: reconic.datasets.xpeng.xpeng_driving_dataset.XpengDrivingDataset
  data_root: /workspace/wangyd13@xiaopeng.com/dataset/xpeng/fm_vision/20
  data_source: vision
  scene_idx: c-43df1bb8-eb78-37af-b4fa-1e0c71f339ad
  dataset: xpeng
  start_timestep: 0 # which timestep to start from
  end_timestep: -1 # which timestep to end at, -1 means the last timestep
  preload_device: cpu # choose from ["cpu", "cuda"], cache the data on this device.
  num_workers: 4
  prefetch_factor: 4
  pixel_source: # image source and object annotations
    type: reconic.datasets.xpeng.xpeng_sourceloader.XpengPixelSource
    cameras: [0, 2, 3, 4, 5, 6, 7]
    downscale_when_loading: [1, 1, 1, 1, 1, 1, 1]
    downscale: 1 # downscale factor wrt to the downscale_when_loading
    difix_downsample: [0.8, 0.8, 0.9, 0.9, 0.9, 0.9, 0.8]
    test_image_stride: 0 # use every Nth timestep for the test set. if 0, use all images for training and none for testing
    load_objects: True # whether to load object bounding boxes
    load_dynamic_mask: True # whether to load image masks
    load_ground_mask: True # whether to load ground masks
    load_sky_mask: True # whether to load sky masks
    load_tfl_mask: True # whether to load tfl masks
    load_smpl: False # whether to load SMPL template for pedestrians
    load_projected_lidar_depth: True # whether to load projected lidar depth
    egocar_dilated_mask: 50 # whether to load ego car mask
    undistort: False # must set to False because it has already been undistorted.
    sampler: # error based image sampler
      ensure_once_per_round: True
      buffer_downscale: 8 # downscale factor for the buffer wrt load_size
      buffer_ratio: 0.0 # the percentage of images sampled according to the error buffer
      start_enhance_weight: 3 # give more chance to sample starting frames, which usually have more errors
  lidar_source: # everything related to "lidar" --- from lidar points
    type: reconic.datasets.xpeng.xpeng_sourceloader.XpengLiDARSource
    load_lidar: True # must set to True
    # ---- compute aabb from lidar ---- #
    # if load_lidar is True, we compute aabb from lidar, otherwise we compute aabb from cameras
    # 1) downsample lidar by random sampling to 1/lidar_downsample_factor number of points
    # 2) compute aabb from the downsampled lidar points by using the percentile of lidar_percentiles
    lidar_downsample_factor: 4 # downsample lidar by this factor to compute percentile
    lidar_percentile: 0.02  # percentile to compute aabb from lidar
# ------------- Trainer ------------ #
recon_trainer:
  type: reconic.trainers.MultiTrainer
  optim:
    num_iters: 30_000
    use_grad_scaler: false
    cache_buffer_freq: -1 # if > 0, use error based image sampler for training
  render:
    render_each_class: true
    near_plane: 0.1 # near plane for rendering
    far_plane: 10000000000.0 # far plane for rendering
    antialiased: false # whether to use antialiasing for gaussian rendering, supported by gsplat kernel
    packed: false # whether to use packed rendering, supported by gsplat kernel
    absgrad: true # whether to use absolute gradient for rendering, supported by gsplat kernel
    sparse_grad: false # whether to use sparse gradient for rendering, supported by gsplat kernel
    batch_size: 1 # batch size for rendering, currently only support 1
  losses:
    rgb:
      w: 1.2
    ssim:
      w: 1.0
    mask:
      w: 0.2
      opacity_loss_type: bce # choose from [bce, safe_bce]
    depth:
      w: 0.1 # weight of depth loss 0.01
      ground_depth_only: False # whether to calculate ground depth loss only
      exclude_dyn_sky: True # whether to exclude dynamic and sky regions for depth loss
      inverse_depth: False # whether to use inverse depth, NOTE that when set to True, must normalize=True
      normalize: False # whether to normalize depth loss
      loss_type: l1 # choose from ["l1", "l2"]
      upper_bound: 20.0 # upper bound of depth value
      depth_error_percentile: 0.95 # percentile of depth error to use for depth loss
    affine:
      w: 0.00005 # weight of affine regularization
    dynamic_opacity:
      w: 0.1 # weight of dynamic opacity loss
      start_from: 15000
    trafficlight:
      rgb_weight: 5.0
    # fake_downwards_cam:
    #   w: 1.0
    #   cam_name: cam2
  gaussian_optim_general_cfg:
    xyz:
      lr: 2.0e-04
      lr_final: 1.6e-06
      scale_factor: 20. # str or float, if "scene_scale", scale the learning rate by the scene scale
    sh_dc:
      lr: 0.0025
    sh_rest:
      lr: 0.000125
    opacity:
      lr: 0.0075 # 0.05 base 0.01
    scaling:
      lr: 0.005
    rotation:
      lr: 0.001
    appearance_features:
      lr: 1e-4
    appearance_embedding_model:
      lr: 1e-4
  gaussian_ctrl_general_cfg:
    warmup_steps: 1300            # warmup steps for alpha
    refine_interval: 60          # refine gaussians every n steps
    sh_degree_interval: 750      # every n intervals turn on another sh degree
    n_split_samples: 2            # number of samples to split gaussians into
    # may differ in different models
    reset_alpha_interval: 3000    # reset alpha every n steps
    reset_alpha_value: 0.01       # reset alpha to this value
    stop_reset_alpha_at: 15000    # stop resetting alpha at this step
    densify_grad_thresh: 0.001    # above this grad, gaussians are densified 0.0005 0.002
    densify_size_thresh: 0.0003   # below this size, gaussians are *duplicated*, otherwise split 0.003 0.0005
    cull_alpha_thresh: 0.005      # threshold of opacity for culling gaussians
    cull_scale_thresh: 0.5        # threshold of scale for culling gaussians
    cull_screen_size: 0.15        # if a gaussian is more than this percent of screen space, cull it
    split_screen_size: 0.05      # if a gaussian is more than this percent of screen space, split it
    stop_screen_size_at: 26250    # stop culling/splitting at this step WRT screen size of gaussians
    stop_split_at: 26250          # stop splitting at this step
    stop_refine_at: 26250         # stop refinement at this step
    sh_degree: 1                  # sh degree for gaussians
    freeze_means: False           # whether to freeze means for gaussians during training
    opacity_loss: False

generative_engine:
  type: reconic.models.generative_models.DifixModel
  scheduler: reconic.engines.SerialScheduler
  max_waiting_queue_size: 0
  base_model_id: nvidia/difix_ref
  pretrained_unet_weights: None
  generate_sky_mask: False
  groundingdino_model_id: ShilongLiu/GroundingDINO
  sam_model_id: facebook/sam-vit-huge
  training_batch_size: -1
  inference_batch_size: 2
  use_8bit_optimizer: False
  dst_size: None
  num_inference_steps: 1
  image_guidance_scale: -1
  guidance_scale: 0.0
  prompts: {
    0: "the Xiaopeng Vehicle of CAM0 camera view.",
    2: "the Xiaopeng Vehicle of CAM2 camera view.",
    3: "the Xiaopeng Vehicle of CAM3 camera view.",
    4: "the Xiaopeng Vehicle of CAM4 camera view.",
    5: "the Xiaopeng Vehicle of CAM5 camera view.",
    6: "the Xiaopeng Vehicle of CAM6 camera view.",
    7: "the Xiaopeng Vehicle of CAM7 camera view.",
  }
  condition_dropout_prob: 0.0
  use_ref_image: True
  use_noncrop_intrinsics: false
  use_mask_in_novel_view: True
  postprocess_cull_ground_gaussians: false
  use_half_novel_view: true
joint_training_cfg:
  start_engine_train_at: -1
  stop_engine_train_at: -1
  start_engine_infer_at: 22000  # 按比例从25000调整为18750
  start_infer_image_index_at: 120
  max_shift: 3.0
  use_max_shift_range: True
  iterations_per_shift: 8000
  use_single_branch_size: False

# ------------- Model ------------ #
model:
  Background:
    type: reconic.models.gaussians.VanillaGaussians
    init:
      from_lidar:
        num_samples: 10_000_000
        return_color: True
        mask_mode: ground_excluded
      far_randoms: 100_000
      near_randoms: 0
      filter_pts_in_boxes: False
      use_feedforawrd: True
    ctrl:
      densify_grad_thresh: 0.002
      densify_size_thresh: 0.0005
    reg:
      sharp_shape_reg:
        w: 1.
        step_interval: 10
        max_gauss_ratio: 2.       # threshold of ratio of gaussian max to min scale before applying regularization loss from the PhysGaussian paper
    optim:
      scaling:
        lr: 0.03
        lr_final: 0.008
  Ground:
    type: reconic.models.gaussians.VanillaGaussians
    init:
      from_lidar:
        return_color: True
        mask_mode: ground_only
      filter_pts_in_boxes: False
      2dgs_init: True
    ctrl:
      reset_alpha_value: 0.2
    #   freeze_means: True
    reg:
      sharp_shape_reg:
        w: 50.0 # 1.
        step_interval: 10
        max_gauss_ratio: 2.
      max_s_square_reg:
        w: 5.0 # 1. 10.0 50.0 100.0
      # sphere_reg:
      #   w_flatten: 1000.0
      #   w_symmetry: 10000.0
    optim:
      xyz:
        lr: 5.0e-05 # 1.6e-04(ori) 5.0e-06(minor) 5.0e-05(increase)
        lr_final: 1.6e-06 # 1.6e-06(ori) 5.0e-07(minor) 1.6e-06(increase)
        scale_factor: 20. 
      scale:
        scaling:
          lr: 0.05
        rotation:
          lr: 0.0002
  Trafficlight:
    type: reconic.models.gaussians.VanillaGaussians
    init:
      from_lidar:
        return_color: True
        model_type : Trafficlight
    ctrl:
      densify_grad_thresh: 0.002
      densify_size_thresh: 0.0005
      fourier_dim: 100
      fourier_scale: 1.0
    reg:
      sharp_shape_reg:
        w: 1.
        step_interval: 10
        max_gauss_ratio: 2.
  RigidNodes:
    type: reconic.models.nodes.RigidNodes
    init:
      instance_max_pts: 20000 # max initial points for each instance
      only_moving: false # only optimize moving instances
      traj_length_thres: 1.0 # threshold of trajectory length for moving instances
      use_feedforawrd: True
    ctrl:
      refine_interval: 60
      reset_alpha_value: 0.15
      cull_scale_thresh: 0.23
      cull_alpha_thresh: 0.008 
      densify_grad_thresh: 0.0018
      densify_size_thresh: 0.0004
      sh_degree: 1
      sh_degree_interval: 750
      warmup_steps: 1000
      cull_out_of_bound: true
      use_plane_fit: false
      cull_scale_max_meters: 0.3
      split_clap: 0.15
      stop_screen_size_at: 26250
      stop_split_at: 26250
      load_rigid_assets: false
      only_retain_dynamic_assets: false
      rigid_assets_base_path: dynamic_assets_ply
    optim:
      scaling:
        lr: 0.008 #0.01
      xyz:
        lr: 0.00012 #0.00016
        lr_final: 1.2e-06
        scale_factor: 20.0
      ins_rotation:
        lr: 0.00001
        lr_final: 0.000005
      ins_translation:
        lr: 0.0005
        lr_final: 0.0001
  RigidNodesLight:
    type: reconic.models.nodes.RigidNodes
    init:
      instance_max_pts: 20000 # max initial points for each instance
      only_moving: false # only optimize moving instances
      traj_length_thres: 1.0 # threshold of trajectory length for moving instances
      use_feedforawrd: True
    ctrl:
      refine_interval: 60
      reset_alpha_value: 0.15
      cull_scale_thresh: 0.23
      cull_alpha_thresh: 0.008 
      densify_grad_thresh: 0.0018
      densify_size_thresh: 0.0004
      sh_degree: 1
      sh_degree_interval: 750
      warmup_steps: 1000
      cull_out_of_bound: true
      use_plane_fit: false
      cull_scale_max_meters: 0.3
      split_clap: 0.15
      stop_screen_size_at: 26250
      stop_split_at: 26250
      load_rigid_assets: false
      only_retain_dynamic_assets: false
      rigid_assets_base_path: dynamic_assets_ply
      fourier_dim: 40
      use_fourier_features: true
      start_frame: 0
    optim:
      scaling:
        lr: 0.008 #0.01
      xyz:
        lr: 0.00012 #0.00016
        lr_final: 1.2e-06
        scale_factor: 20.0
      ins_rotation:
        lr: 0.00001
        lr_final: 0.000005
      ins_translation:
        lr: 0.0005
        lr_final: 0.0001
  SMPLNodes: 
    type: reconic.models.nodes.SMPLNodes
    init:
      only_moving: true
      traj_length_thres: 0.5
    reg:
      sharp_shape_reg:
        w: 1.
        step_interval: 10
        max_gauss_ratio: 10.
      temporal_smooth_reg:
        trans:
          w: 0.01 # optimal value may vary
          smooth_range: 5 # range of frames to consider for smoothing
        # joint_smooth:
        #   w: 0.01 # optimal value may vary
      knn_reg:
        # lambda_std_x: 0.0001
        lambda_std_q: 0.001
        lambda_std_s: 0.001
        lambda_std_o: 0.001
        lambda_std_shs_dc: 0.001
        lambda_std_shs_rest: 0.001
      max_s_square_reg:
        w: 0.05
      x_offset:
        w: 0.2
      voxel_deformer_reg:
        lambda_std_w: 0.6
        lambda_std_w_rest: 0.5
        lambda_w_norm: 0.6
        lambda_w_rest_norm: 0.3
    optim:
      xyz:
        lr: 1.6e-04
        lr_final: 1.6e-06
        scale_factor: 3.0
      rotation:
        lr: 0.005
      sh_dc:
        lr: 0.005
      sh_rest:
        lr: 0.00025
      ins_rotation:
        lr: 0.00001
        lr_final: 0.000005
      ins_translation:
        lr: 0.0005
        lr_final: 0.0001
      smpl_rotation:
        lr: 0.00005
        lr_final: 0.00001
      w_dc_vox:
        lr: 0.0001
        lr_final: 0.00001
        opt_after: 10000
    ctrl:
      sh_degree: 1
      opacity_init_value: 0.99
      ball_gaussians: false
      constrain_xyz_offset: false
      knn_update_interval: 100
      knn_neighbors: 3
      use_voxel_deformer: true
      freeze_x: false
      freeze_o: false
      freeze_q: false
      freeze_s: false
      freeze_shs_dc: false
      freeze_shs_rest: false
  Sky:
    type: reconic.models.modules.SkyModel
    params:
      head_mlp_layer_width: 64
      enable_appearance_embedding: True
      appearance_embedding_dim: 16
      mode: first_frame_sky_only  # choose from [default, sky_only, first_frame_sky_only]
    optim:
      all:
        lr: 0.01
  Affine:
    type: reconic.models.modules.AffineTransform
    params:
      embedding_dim: 4
      base_mlp_layer_width: 64
      pixel_affine: False
      use_random_init: True
      use_camera_embedding: False
      # apply_camera_names: ["cam0", "cam2", "cam7"]
    optim:
      all:
        lr: 1.0e-3
        lr_final: 1.0e-4
        warmup_steps: 1000
        max_steps: 30000  # 从40000改为30000
        lr_pre_warmup: 1.0e-7
        ramp: cosine
        weight_decay: 1.0e-6
  CamPose:
    type: reconic.models.modules.CameraOptModule
    params:
      use_random_init: False
    optim:
      all:
        lr: 1.0e-5
        weight_decay: 1.0e-6

# ------------- render ------------ #
render:
  compute_metrics: false
  fps: 10 # frames per second for the main rendered output
  redistort_rgb: True # whether to redistort rgb images
  render_full: False # whether to render full resolution videos
  render_test: False # whether to render test set
  render_novel:
    render: False
    traj_types:
    - type: relative_lane_shift
      direction: x
      distance: 3.0
      render_name: lane_shift_left_3m
    - type: relative_lane_shift
      direction: x
      distance: -3.0
      render_name: lane_shift_right_3m
    fps: 10 # frames per second for novel view rendering
  vis_lidar: False # whether to visualize lidar points on ground truth images
  vis_sky: True # whether to include "rgb_sky" and "rgb_sky_blend" in rendered keys
  vis_error: False # whether to include "rgb_error_map" in rendered keys
  with_image_output: False # whether to save images

# --------------- fixer ------------- #
fixer:
  cam:
  - 0
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  compile_pipeline: false
  fp16: true
  guidance_scale: 3.0
  pretrained_path: /workspace/group_share/adc-sim/users/led/ckpts/difix
  prompt: remove degradation
  scale: 1
  timesteps:
  - 200
  use_reference_image: false
  xformers: true

# ------------- logging ------------ #
logging:
  vis_freq: 2000 # how often to visualize training stats
  print_freq: 500 # how often to print training stats
  saveckpt_freq: 80000 # how often to save checkpoints
  save_seperate_video: True # whether to save seperate videos for each scene

# ------------- visualizer ------------ #
visualizer:
  enable_wandb: False
  enable_viewer: False

# ------------- metrics --------------- #
metrics:
  batch_size: 64
  eval_image_path: novel_view_data
  detection:
    model_path: /workspace/wenkang.qin@gigaai.cc/pretrain_model/yolo11m.pt
    model_input_size: [640, 640]
    id_classname_in_model: {0: "pedestrian",
                            1: "cyclist",
                            2: "car",
                            3: "motorcycle",
                            5: "bus",
                            7: "truck"
    }
    confidence_threshold: 0.0
    iou_threshold: 0.3
    classid_name: {0: "vehicle", 1: "pedestrian", 2: "cyclist", 3: "motorcycle"}
    detection_scope: 100
    bbox_minimal_area: 4
  fid:
    image_size: [640, 960]
