datasets:
  - dataset_name: vision_dataset_1021
    root: /workspace/yangxh7@xiaopeng.com/datasets/xpeng/ppu_full_depth
    clip_id: c-93d52601-92a8-3c57-b56d-50ea05b2c9d2
    trigger_time_offset_map:
      "摆动/蛇形": {takeover: 10, issue: 5}
      "变道/绕行不合理": {takeover: 10, issue: 5}
      "不加速/加速慢": {takeover: 10, issue: 5}
      "不减速/制动不足": {takeover: 5, issue: 3}
      "不居中/贴边": {takeover: 10, issue: 5}
      "方向盘摆动/抖动": {takeover: 5, issue: 3}
      "跟/停距离远": {takeover: 5, issue: 3}
      "红绿灯相关问题": {takeover: 5, issue: 3}
      "加减速顿挫": {takeover: 10, issue: 5}
      "路口路径不合理": {takeover: 10, issue: 5}
      "逆向目标避让不足": {takeover: 5, issue: 3}
      "危险变道/绕行": {takeover: 5, issue: 3}
      "未及时变道/绕行": {takeover: 15, issue: 10}
      "压线": {takeover: 10, issue: 5}
      "异常减速": {takeover: 5, issue: 3}
      "撞路沿/障碍物": {takeover: 5, issue: 3}
      "不发起导航变道/过晚": {takeover: 10, issue: 5}
      "进逆向车道": {takeover: 10, issue: 5}
      "溜车": {takeover: 5, issue: 3}
      "不礼让行人": {takeover: 5, issue: 3}
      "主辅路/分合流未跟导航": {takeover: 10, issue: 5}
      "路口通行未跟导航": {takeover: 10, issue: 5}
    enable_canbus_topic: True
    canbus_topic_list:
      - DynamicXNetTopic
      - StaticXNetTopic
      - MfLocalPoseTopic
      - SensorFusionTopic
      # - StateManagementTopic
    ips_deploy: True
    use_raw_localpose: True
    steps_controller:
      source: vision
      vision_data_fetcher: False
      json_processor: True
      img_processor: True
      opt_processor: True
      sam3d_processor: True
      pose_processor: True
      mvsnet_processor: True
      ground_processor: True
      pcd_fusion_processor: True
      colmap_processor: False
      point_densifier: False
      point_processor: True
      depth_processor: True
      evosplat_processor: True
      trafficlight_processor: True
    processor:
      object_bbox_src: "dxnet"
    ground_processor:
      z_weight_from_mvsnet: 0.01
    depth_processor:
      depth_source: "complete"
