import os
import gc
import lpips
import random
import argparse
import shutil
import sys
import numpy as np
import torch
import torch.nn.functional as F
import torchvision
import transformers
import json
from torchvision.transforms.functional import crop
from accelerate import Accelerator
from accelerate.utils import set_seed
from PIL import Image
from torchvision import transforms
from glob import glob
from einops import rearrange
from collections import defaultdict

import diffusers
from diffusers.utils.import_utils import is_xformers_available
from diffusers.optimization import get_scheduler
from diffusers import utils as diffusers_utils
from diffusers.utils import dynamic_modules_utils as diffusers_dynamic_modules_utils

from torch.utils.tensorboard import SummaryWriter

from model import Difix, load_ckpt_from_state_dict
from dataset import PairedDataset, CamGroupedBatchSampler
from loss import gram_loss
from pipeline_difix import DifixPipeline
from utils_difix import calculate_psnr, save_config
from config_train import save_checkpoint_for_epoch as save_checkpoint_for_epoch_impl


def _cleanup_diffusers_dynamic_local_cache():
    """Remove potentially corrupted dynamic module cache generated by diffusers."""
    modules_cache_root = diffusers_dynamic_modules_utils.HF_MODULES_CACHE
    local_dynamic_dir = os.path.join(modules_cache_root, "diffusers_modules", "local")
    if os.path.isdir(local_dynamic_dir):
        shutil.rmtree(local_dynamic_dir, ignore_errors=True)


def _set_rank_scoped_hf_modules_cache(accelerator):
    """
    Use rank-scoped HF dynamic module cache to avoid write races across processes.
    """
    modules_cache_root = os.environ.get("HF_MODULES_CACHE")
    if not modules_cache_root:
        modules_cache_root = os.path.join(
            os.environ.get("HF_HOME", os.path.expanduser("~/.cache/huggingface")),
            "modules",
        )
    rank_cache_root = os.path.join(modules_cache_root, f"rank_{accelerator.process_index}")
    os.makedirs(rank_cache_root, exist_ok=True)
    os.environ["HF_MODULES_CACHE"] = rank_cache_root
    # IMPORTANT: diffusers caches HF_MODULES_CACHE in module-level constants at import time.
    # Update both constants so runtime uses rank-scoped cache immediately.
    diffusers_utils.HF_MODULES_CACHE = rank_cache_root
    diffusers_dynamic_modules_utils.HF_MODULES_CACHE = rank_cache_root
    if rank_cache_root not in sys.path:
        sys.path.append(rank_cache_root)


def _load_pipeline_with_distributed_guard(accelerator, pipeline_name):
    """
    Load pipeline safely in multi-process mode.
    - Use rank-scoped dynamic-module cache to avoid cross-rank write races.
    - Retry once if local dynamic module cache is corrupted.
    """
    _set_rank_scoped_hf_modules_cache(accelerator)
    last_err = None
    for attempt in range(2):
        if attempt > 0:
            print(
                f"[rank {accelerator.process_index}] retry loading pipeline after cleaning dynamic cache...",
                flush=True,
            )
            _cleanup_diffusers_dynamic_local_cache()
        try:
            pipe = DifixPipeline.from_pretrained(
                pipeline_name,
                trust_remote_code=True,
                local_files_only=True,
            )
        except AttributeError as err:
            last_err = err
            if "diffusers_modules.local.unet_2d_condition" not in str(err):
                raise
            print(
                f"[rank {accelerator.process_index}] dynamic module load failed: {err}",
                flush=True,
            )
        else:
            return pipe
    raise RuntimeError(
        "Failed to load DifixPipeline after retry. "
        "Please check local model files and dynamic module cache."
    ) from last_err


def main(args):
    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=args.report_to,
        project_dir=os.path.join(args.output_dir, "tensorboard")
    )

    if accelerator.is_local_main_process:
        transformers.utils.logging.set_verbosity_warning()
        diffusers.utils.logging.set_verbosity_info()
    else:
        transformers.utils.logging.set_verbosity_error()
        diffusers.utils.logging.set_verbosity_error()

    if args.seed is not None:
        set_seed(args.seed)

    if accelerator.is_main_process:
        os.makedirs(os.path.join(args.output_dir, "checkpoints"), exist_ok=True)
        os.makedirs(os.path.join(args.output_dir, "eval"), exist_ok=True)
    
    # save the config
    save_config(args.output_dir, args)
        
    # make the model
    use_ref_img = getattr(args, "use_ref_img", False)
    pipeline_name = "nvidia/difix_ref" if use_ref_img else "nvidia/difix"
    pipe = _load_pipeline_with_distributed_guard(accelerator, pipeline_name)
    pipe.to(accelerator.device)
    
    net_difix = Difix(
        pipe=pipe,
        lora_rank_vae=args.lora_rank_vae, 
        timestep=args.timestep,
    )
    net_difix.set_train()

    # setup the model
    if args.enable_xformers_memory_efficient_attention:
        if is_xformers_available():
            net_difix.unet.enable_xformers_memory_efficient_attention()
        else:
            raise ValueError("xformers is not available, please install it by running `pip install xformers`")

    if args.gradient_checkpointing:
        net_difix.unet.enable_gradient_checkpointing()

    if args.allow_tf32:
        torch.backends.cuda.matmul.allow_tf32 = True

    net_lpips = lpips.LPIPS(net='vgg').cuda()
    net_lpips.requires_grad_(False)
    net_vgg = torchvision.models.vgg16(pretrained=True).features
    for param in net_vgg.parameters():
        param.requires_grad_(False)

    # make the optimizer
    layers_to_opt = []
    layers_to_opt += list(net_difix.unet.parameters())
   
    for n, _p in net_difix.vae.named_parameters():
        if "lora" in n and "vae_skip" in n:
            assert _p.requires_grad
            layers_to_opt.append(_p)
    layers_to_opt = layers_to_opt + list(net_difix.vae.decoder.skip_conv_1.parameters()) + \
        list(net_difix.vae.decoder.skip_conv_2.parameters()) + \
        list(net_difix.vae.decoder.skip_conv_3.parameters()) + \
        list(net_difix.vae.decoder.skip_conv_4.parameters())

    optimizer = torch.optim.AdamW(layers_to_opt, lr=args.learning_rate,
        betas=(args.adam_beta1, args.adam_beta2), weight_decay=args.adam_weight_decay,
        eps=args.adam_epsilon,)

    # make the dataset
    overwrite_prompt = getattr(args, "overwrite_prompt", None)
    if isinstance(overwrite_prompt, str):
        overwrite_prompt = overwrite_prompt.strip()
    if overwrite_prompt == "":
        overwrite_prompt = None
    if accelerator.is_main_process and overwrite_prompt is not None:
        print(f"[PROMPT] overwrite_prompt is enabled: {overwrite_prompt}", flush=True)

    use_ref_mask = bool(getattr(args, "use_ref_mask", False))
    dataset_train = PairedDataset(
        dataset_path=args.dataset_path, split="train", tokenizer=net_difix.tokenizer,
        height=args.image_height, width=args.image_width,
        enable_dual_resolution_bucket=args.enable_dual_resolution_bucket,
        bucket_16_9_height=args.bucket_16_9_height,
        bucket_16_9_width=args.bucket_16_9_width,
        bucket_5_4_height=args.bucket_5_4_height,
        bucket_5_4_width=args.bucket_5_4_width,
        use_ref_img=use_ref_img,
        overwrite_prompt=overwrite_prompt,
        ref_perturb_prob=getattr(args, "ref_perturb_prob", 0.0),
        ref_perturb_amp=getattr(args, "ref_perturb_amp", 10.0),
        ref_perturb_repr_depth=getattr(args, "ref_perturb_repr_depth", 15.0),
        use_ref_mask=use_ref_mask,
    )
    if accelerator.is_main_process and getattr(args, "ref_perturb_prob", 0.0) > 0:
        print(
            f"[ref_perturb] enabled on train set: prob={args.ref_perturb_prob}, "
            f"amp={args.ref_perturb_amp}, repr_depth={args.ref_perturb_repr_depth}",
            flush=True,
        )
    if accelerator.is_main_process and use_ref_mask:
        print("[ref_mask] enabled: train/val 会读取数据 JSON 中的 'ref_mask' 字段并在 attn1 中屏蔽", flush=True)
    batch_sampler = CamGroupedBatchSampler(
        dataset_train, batch_size=args.train_batch_size, drop_last=False
    )
    dl_train = torch.utils.data.DataLoader(
        dataset_train, batch_sampler=batch_sampler, num_workers=args.dataloader_num_workers
    )
    
    dataset_val = PairedDataset(
        dataset_path=args.dataset_path, split="test", tokenizer=net_difix.tokenizer,
        height=args.image_height, width=args.image_width,
        enable_dual_resolution_bucket=args.enable_dual_resolution_bucket,
        bucket_16_9_height=args.bucket_16_9_height,
        bucket_16_9_width=args.bucket_16_9_width,
        bucket_5_4_height=args.bucket_5_4_height,
        bucket_5_4_width=args.bucket_5_4_width,
        use_ref_img=use_ref_img,
        overwrite_prompt=overwrite_prompt,
        use_ref_mask=use_ref_mask,
    )
    dl_val = torch.utils.data.DataLoader(dataset_val, batch_size=1, shuffle=False, num_workers=0)

    # Resume from checkpoint
    global_step = 0
    resume_info = {}
    if args.resume is not None:
        if os.path.isdir(args.resume):
            # Resume from last ckpt (e.g. checkpoints/model.pkl or checkpoints_epoch_*/model.pkl)
            ckpt_files = glob(os.path.join(args.resume, "*.pkl"))
            assert len(ckpt_files) > 0, f"No checkpoint files found: {args.resume}"
            # 可能为 model.pkl 或 model_123.pkl
            def _step_from_path(p):
                name = os.path.basename(p).replace(".pkl", "")
                if name == "model":
                    return 0
                return int(name.replace("model_", ""))
            ckpt_files = sorted(ckpt_files, key=_step_from_path)
            ckpt_path = ckpt_files[-1]
            print("="*50); print(f"Loading checkpoint from {ckpt_path}"); print("="*50)
            net_difix, optimizer, resume_info = load_ckpt_from_state_dict(
                net_difix, ckpt_path, optimizer
            )
            if resume_info.get("global_step") is not None:
                global_step = resume_info["global_step"]
            else:
                global_step = _step_from_path(ckpt_path)
        elif args.resume.endswith(".pkl"):
            print("="*50); print(f"Loading checkpoint from {args.resume}"); print("="*50)
            net_difix, optimizer, resume_info = load_ckpt_from_state_dict(
                net_difix, args.resume, optimizer
            )
            if resume_info.get("global_step") is not None:
                global_step = resume_info["global_step"]
            else:
                global_step = int(args.resume.split("/")[-1].replace("model_", "").replace(".pkl", ""))
        else:
            raise NotImplementedError(f"Invalid resume path: {args.resume}")
        print(f"Resume info: global_step={global_step}, resume_info={resume_info}")
    else:
        print("="*50); print(f"Training from scratch"); print("="*50)
    
    # make the weight dtype
    weight_dtype = torch.float32
    if accelerator.mixed_precision == "fp16":
        weight_dtype = torch.float16
    elif accelerator.mixed_precision == "bf16":
        weight_dtype = torch.bfloat16

    # Move al networksr to device and cast to weight_dtype
    net_difix.to(accelerator.device, dtype=weight_dtype)
    net_lpips.to(accelerator.device, dtype=weight_dtype)
    net_vgg.to(accelerator.device, dtype=weight_dtype)
    
    # Prepare everything with our `accelerator`.
    net_difix, optimizer, dl_train, dl_val = accelerator.prepare(
        net_difix, optimizer, dl_train, dl_val
    )
    num_update_steps_per_epoch = len(dl_train)
    total_train_steps = num_update_steps_per_epoch * args.num_training_epochs
    lr_scheduler = get_scheduler(
        args.lr_scheduler,
        optimizer=optimizer,
        num_warmup_steps=args.lr_warmup_steps,
        num_training_steps=total_train_steps,
        num_cycles=args.lr_num_cycles,
        power=args.lr_power,
    )
    # 从 ckpt 恢复 epoch（及 lr_scheduler）
    start_epoch = 0
    if resume_info:
        if resume_info.get("epoch") is not None:
            start_epoch = int(resume_info["epoch"])
        elif resume_info.get("global_step") is not None:
            start_epoch = resume_info["global_step"] // num_update_steps_per_epoch
        if resume_info.get("lr_scheduler_state") is not None:
            lr_scheduler.load_state_dict(resume_info["lr_scheduler_state"])
    if accelerator.is_main_process:
        global_batch_size = args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps
        print(
            f"Distributed setup: world_size={accelerator.num_processes}, "
            f"per_device_batch={args.train_batch_size}, global_batch={global_batch_size}"
        )
        print(
            f"Scheduler total_train_steps={total_train_steps} "
            f"(steps_per_epoch={num_update_steps_per_epoch}, epochs={args.num_training_epochs})"
        )
        if start_epoch > 0:
            print(f"Resume: start_epoch={start_epoch}, global_step={global_step}")
    net_lpips, net_vgg = accelerator.prepare(net_lpips, net_vgg)
    # renorm with image net statistics
    t_vgg_renorm =  transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))

    # We need to initialize the trackers we use, and also store our configuration.
    # The trackers initializes automatically on the main process (tensorboard).
    if accelerator.is_main_process:
        tracker_config = dict(vars(args))
        accelerator.init_trackers(args.tracker_project_name, config=tracker_config)

    def save_checkpoint_for_epoch(epoch_idx, current_global_step, lr_scheduler=None, is_final=False):
        save_checkpoint_for_epoch_impl(
            accelerator, net_difix, optimizer, args,
            epoch_idx, current_global_step,
            lr_scheduler=lr_scheduler, is_final=is_final,
        )

    def _evaluate_test_psnr():
        """
        Evaluate PSNR on the whole test split.
        Returns:
            eval_logs: dict containing eval_psnr/overall and eval_psnr/cam_xxx.
        """
        eval_logs = {}
        if len(dataset_val) == 0:
            print("[EVAL] test set is empty, skip PSNR evaluation.", flush=True)
            return eval_logs

        eval_cam_names = list(
            getattr(dataset_val, "cam_names", ("cam0", "cam2", "cam3", "cam4", "cam5", "cam6", "cam7"))
        )
        cam_to_idx = {cam: i for i, cam in enumerate(eval_cam_names)}
        local_psnr_sum = torch.zeros(len(eval_cam_names), device=accelerator.device, dtype=torch.float64)
        local_psnr_cnt = torch.zeros(len(eval_cam_names), device=accelerator.device, dtype=torch.float64)
        local_eval_samples = 0
        local_eval_batches = 0

        print(
            f"[EVAL][RANK {accelerator.process_index}] start: "
            f"dataset_val_len={len(dataset_val)}, local_dl_batches={len(dl_val)}",
            flush=True,
        )

        unwrapped_model = accelerator.unwrap_model(net_difix)
        unwrapped_model.set_eval()
        try:
            with torch.no_grad():
                for batch_val in dl_val:
                    local_eval_batches += 1
                    x_src_val = batch_val["conditioning_pixel_values"].to(
                        accelerator.device, dtype=weight_dtype
                    )
                    x_tgt_val = batch_val["output_pixel_values"]
                    ref_mask_val = batch_val.get("ref_mask", None)
                    if ref_mask_val is not None:
                        ref_mask_val = ref_mask_val.to(accelerator.device, dtype=weight_dtype)
                    x_pred_val = net_difix(
                        x_src_val,
                        prompt_tokens=batch_val["input_ids"],
                        ref_mask=ref_mask_val,
                    )

                    batch_size_val = x_pred_val.shape[0]
                    local_eval_samples += int(batch_size_val)
                    for b in range(batch_size_val):
                        cam_name = batch_val["cam_name"][b]
                        origin_w = int(batch_val["origin_input_width"][b])
                        origin_h = int(batch_val["origin_input_height"][b])

                        pred_img = transforms.ToPILImage()(
                            x_pred_val[b, 0, ...].detach().cpu().float() * 0.5 + 0.5
                        ).resize((origin_w, origin_h), Image.LANCZOS)
                        tgt_img = transforms.ToPILImage()(
                            x_tgt_val[b, 0, ...].detach().cpu().float() * 0.5 + 0.5
                        ).resize((origin_w, origin_h), Image.LANCZOS)

                        mask_np = batch_val["mask"][b, 0, ...].detach().cpu().numpy().astype(np.uint8)
                        if mask_np.shape[:2] != (origin_h, origin_w):
                            mask_np = np.array(
                                Image.fromarray(mask_np).resize((origin_w, origin_h), Image.NEAREST)
                            )

                        psnr_val = calculate_psnr(pred_img, tgt_img, mask_np)
                        if np.isfinite(psnr_val):
                            if cam_name in cam_to_idx:
                                cam_idx = cam_to_idx[cam_name]
                                local_psnr_sum[cam_idx] += float(psnr_val)
                                local_psnr_cnt[cam_idx] += 1.0
        finally:
            # restore training mode no matter eval success/failure
            unwrapped_model.set_train()
        print(
            f"[EVAL][RANK {accelerator.process_index}] done: "
            f"local_samples={local_eval_samples}, local_batches={local_eval_batches}",
            flush=True,
        )
        # 所有 rank 共同参与评估，汇总到 main 进程记录
        global_psnr_sum = accelerator.reduce(local_psnr_sum, reduction="sum")
        global_psnr_cnt = accelerator.reduce(local_psnr_cnt, reduction="sum")

        if accelerator.is_main_process:
            total_sum = 0.0
            total_cnt = 0.0
            for cam_idx, cam_name in enumerate(eval_cam_names):
                cnt = float(global_psnr_cnt[cam_idx].item())
                if cnt > 0:
                    s = float(global_psnr_sum[cam_idx].item())
                    eval_logs[f"eval_psnr/cam_{cam_name}"] = s / cnt
                    total_sum += s
                    total_cnt += cnt
            if total_cnt > 0:
                eval_logs["eval_psnr/overall"] = total_sum / total_cnt
            else:
                print("[EVAL] no valid PSNR values found on test set.", flush=True)
        return eval_logs

    if args.resume is None:
        accelerator.wait_for_everyone()
        save_checkpoint_for_epoch(0, global_step, lr_scheduler=lr_scheduler)
        accelerator.wait_for_everyone()

    init_eval_logs = _evaluate_test_psnr()
    if accelerator.is_main_process and len(init_eval_logs) > 0:
        init_eval_display = ", ".join(
            f"{k}={v:.4f}" for k, v in sorted(init_eval_logs.items())
        )
        print(
            f"[EVAL][INIT] step={global_step}: {init_eval_display}",
            flush=True,
        )
        accelerator.log(init_eval_logs, step=global_step)

    # start the training loop（resume 时从 start_epoch 继续）
    # 已见图片数 = global_step × (train_batch_size × GPU数 × gradient_accumulation_steps)
    # 可用 config_train.step_to_num_images(step, args.train_batch_size, args.gradient_accumulation_steps, accelerator.num_processes) 计算
    for epoch in range(start_epoch, args.num_training_epochs):
        if hasattr(batch_sampler, "set_epoch"):
            batch_sampler.set_epoch(epoch)
        for step, batch in enumerate(dl_train):
            if step >= args.max_steps_per_epoch:
                break
            l_acc = [net_difix]
            with accelerator.accumulate(*l_acc):
                cam_names = batch["cam_name"]
                x_src = batch["conditioning_pixel_values"]
                x_tgt = batch["output_pixel_values"]
                B, V, C, H, W = x_src.shape

                ref_mask_batch = batch.get("ref_mask", None)
                if ref_mask_batch is not None:
                    ref_mask_batch = ref_mask_batch.to(x_src.device, dtype=x_src.dtype)

                # forward pass
                x_tgt_pred = net_difix(
                    x_src,
                    prompt_tokens=batch["input_ids"],
                    ref_mask=ref_mask_batch,
                )       
                
                x_tgt = rearrange(x_tgt, 'b v c h w -> (b v) c h w')
                x_tgt_pred = rearrange(x_tgt_pred, 'b v c h w -> (b v) c h w')
                # mask 
                x_mask = (batch["mask"] > 1).unsqueeze(1).expand(-1, V, -1, -1, -1)  # (B, 1, H, W) -> (B, V, 1, H, W)
                x_mask = rearrange(x_mask.float(), 'b v c h w -> (b v) c h w')
                if x_mask.shape[-2:] != x_tgt.shape[-2:]:
                    x_mask = F.interpolate(x_mask, size=x_tgt.shape[-2:], mode='nearest')
                x_mask = x_mask.expand_as(x_tgt)
                
                # 与论文一致：View0 修复目标图，View1 恒等约束（ref→ref），对两 view 的 loss 取平均
                # 见 DIFIX3D+ Figure 3 / Section 4.1：对 View1 算 loss 保持特征一致、避免破坏 Reference Mixing
                def masked_mse_per_item(pred, tgt, mask):
                    diff_sq = (pred - tgt) ** 2
                    num_masked = mask.sum(dim=(1, 2, 3)).clamp(min=1)
                    return (diff_sq * mask).sum(dim=(1, 2, 3)) / num_masked
                def masked_l1_per_item(pred, tgt, mask):
                    diff = (pred - tgt).abs()
                    num_masked = mask.sum(dim=(1, 2, 3)).clamp(min=1)
                    return (diff * mask).sum(dim=(1, 2, 3)) / num_masked
                loss_l2_per_bv = masked_mse_per_item(x_tgt_pred.float(), x_tgt.float(), x_mask) * args.lambda_l2
                loss_l2_per_sample = rearrange(loss_l2_per_bv, '(b v) -> b v', v=V).mean(dim=1)
                loss_l2 = loss_l2_per_sample.mean()
                # LPIPS: 仅在 mask 区域计算，将非 mask 区域置为相同值使该区域贡献为 0
                lpips_param = next(net_lpips.parameters())
                x_tgt_masked = (x_tgt.float() * x_mask).to(device=lpips_param.device, dtype=lpips_param.dtype)
                x_tgt_pred_masked = (x_tgt_pred.float() * x_mask).to(device=lpips_param.device, dtype=lpips_param.dtype)
                loss_lpips_per_bv = net_lpips(x_tgt_pred_masked, x_tgt_masked).flatten()
                if loss_lpips_per_bv.dim() == 0:
                    loss_lpips_per_bv = loss_lpips_per_bv.unsqueeze(0)
                loss_lpips_per_sample = rearrange(loss_lpips_per_bv * args.lambda_lpips, '(b v) -> b v', v=V).mean(dim=1)
                loss_lpips = loss_lpips_per_sample.mean()
                loss = loss_l2 + loss_lpips
                
                # Gram matrix loss (crop 后对 mask 区域应用)
                if args.lambda_gram > 0:
                    if global_step > args.gram_loss_warmup_steps:
                        x_tgt_pred_renorm = t_vgg_renorm(x_tgt_pred * 0.5 + 0.5)
                        crop_h, crop_w = 400, 400
                        top, left = random.randint(0, H - crop_h), random.randint(0, W - crop_w)
                        x_tgt_pred_renorm = crop(x_tgt_pred_renorm, top, left, crop_h, crop_w)
                        
                        x_tgt_renorm = t_vgg_renorm(x_tgt * 0.5 + 0.5)
                        x_tgt_renorm = crop(x_tgt_renorm, top, left, crop_h, crop_w)
                        
                        x_mask_crop = crop(x_mask, top, left, crop_h, crop_w)
                        x_tgt_pred_renorm = (x_tgt_pred_renorm * x_mask_crop).to(weight_dtype)
                        x_tgt_renorm = (x_tgt_renorm * x_mask_crop).to(weight_dtype)
                        
                        loss_gram = gram_loss(x_tgt_pred_renorm, x_tgt_renorm, net_vgg) * args.lambda_gram
                        loss += loss_gram
                    else:
                        loss_gram = torch.tensor(0.0).to(weight_dtype)                        
                loss_total_per_sample = loss_l2_per_sample + loss_lpips_per_sample
                    
                accelerator.backward(loss, retain_graph=False)
                if accelerator.sync_gradients:
                    accelerator.clip_grad_norm_(layers_to_opt, args.max_grad_norm)
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad(set_to_none=args.set_grads_to_none)
                
                x_tgt = rearrange(x_tgt, '(b v) c h w -> b v c h w', v=V)
                x_tgt_pred = rearrange(x_tgt_pred, '(b v) c h w -> b v c h w', v=V)

            # Checks if the accelerator has performed an optimization step behind the scenes
            if accelerator.sync_gradients:
                global_step += 1

                eval_logs = {}
                if args.eval_freq > 0 and global_step % args.eval_freq == 0:
                    eval_logs = _evaluate_test_psnr()

                if accelerator.is_main_process:
                    logs = {}
                    for cam in set(cam_names):
                        idx = [i for i, c in enumerate(cam_names) if c == cam]
                        logs[f"loss/cam_{cam}"] = loss_total_per_sample.detach()[idx].mean().item()
                    
                    # log all the losses
                    logs["loss/total"] = loss.detach().item()
                    logs["loss_l2"] = loss_l2.detach().item()
                    logs["loss_lpips"] = loss_lpips.detach().item()
                    if args.lambda_gram > 0:
                        logs["loss_gram"] = loss_gram.detach().item()
                    
                    def _scalar_for_display(v):
                        if isinstance(v, (int, float)):
                            return v
                        if isinstance(v, (np.floating, np.integer)):
                            return float(v)
                        if hasattr(v, "item"):  # tensor or 0-dim array
                            return v.item()
                        return v
                    display_logs = {
                        k: _scalar_for_display(v) for k, v in logs.items()
                        if isinstance(v, (int, float, np.floating, np.integer))
                        or (hasattr(v, "item") and getattr(v, "ndim", -1) == 0)
                    }
                    display_items = ", ".join(
                        f"{k}={v:.4g}" if isinstance(v, (int, float, np.floating, np.integer))
                        else f"{k}={v}"
                        for k, v in sorted(display_logs.items())
                    )
                    print(f"[EPOCH {epoch}] step={global_step}: {display_items}", flush=True)
                    
                    # viz some images (TensorBoard)
                    if global_step % args.viz_freq == 1:
                        for tracker in accelerator.trackers:
                            if hasattr(tracker, "writer") and isinstance(tracker.writer, SummaryWriter):
                                for idx in range(B):
                                    img_src = rearrange(x_src, "b v c h w -> b c (v h) w")[idx].float().detach().cpu() * 0.5 + 0.5
                                    img_tgt = rearrange(x_tgt, "b v c h w -> b c (v h) w")[idx].float().detach().cpu() * 0.5 + 0.5
                                    img_pred = rearrange(x_tgt_pred, "b v c h w -> b c (v h) w")[idx].float().detach().cpu() * 0.5 + 0.5
                                    tracker.writer.add_image(f"train/source_{idx}", img_src.clamp(0, 1), global_step)
                                    tracker.writer.add_image(f"train/target_{idx}", img_tgt.clamp(0, 1), global_step)
                                    tracker.writer.add_image(f"train/model_output_{idx}", img_pred.clamp(0, 1), global_step)
                                break

                    if len(eval_logs) > 0:
                        logs.update(eval_logs)
                        eval_display = ", ".join(
                            f"{k}={v:.4f}" for k, v in sorted(eval_logs.items())
                        )
                        print(
                            f"[EVAL][EPOCH {epoch}] step={global_step}: {eval_display}",
                            flush=True,
                        )
                    accelerator.log(logs, step=global_step)

        if args.checkpointing_epoch > 0 and (epoch + 1) % args.checkpointing_epoch == 0:
            accelerator.wait_for_everyone()
            save_checkpoint_for_epoch(epoch + 1, global_step, lr_scheduler=lr_scheduler)
            accelerator.wait_for_everyone()

    accelerator.wait_for_everyone()
    save_checkpoint_for_epoch(args.num_training_epochs, global_step, lr_scheduler=lr_scheduler, is_final=True)
    accelerator.wait_for_everyone()


if __name__ == "__main__":
    from config_train import parse_config_args
    args = parse_config_args()
    main(args)
