MODELS_PATH: "./harmonization_exps_hr/models"
EXPS_PATH: "./harmonization_exps_hr"

# HFLICKR_PATH: "/S4/MI/xueb/data/IDIH/HFlickr"
# HDAY2NIGHT_PATH: "/S4/MI/xueb/data/IDIH/Hday2night"
# HCOCO_PATH: "/S4/MI/xueb/data/IDIH/HCOCO"
# HADOBE5K_PATH: "/S4/MI/xueb/data/IDIH/HAdobe5k"
7A9F_22963641_CAM0_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-22963641/cam0"
62BF_22968102_CAM0_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-b0b0a536-2131-3812-ac64-a99f1c1a62bf-22968102/cam0"

TEST_9DD9_22963670_CAM0_PATH: "/workspace/duanzx@xiaopeng.com/code/AICT-main/iHarmony4/test/c-f560ab8e-0f35-31fe-8e57-36a00fe39dd9-22963670/cam0"
TEST_9DD9_22963670_CAM2_PATH: "/workspace/duanzx@xiaopeng.com/code/AICT-main/iHarmony4/test/c-f560ab8e-0f35-31fe-8e57-36a00fe39dd9-22963670/cam2"
TEST_9DD9_22963670_CAM3_PATH: "/workspace/duanzx@xiaopeng.com/code/AICT-main/iHarmony4/test/c-f560ab8e-0f35-31fe-8e57-36a00fe39dd9-22963670/cam3"
TEST_9DD9_22963670_CAM4_PATH: "/workspace/duanzx@xiaopeng.com/code/AICT-main/iHarmony4/test/c-f560ab8e-0f35-31fe-8e57-36a00fe39dd9-22963670/cam4"
TEST_9DD9_22963670_CAM5_PATH: "/workspace/duanzx@xiaopeng.com/code/AICT-main/iHarmony4/test/c-f560ab8e-0f35-31fe-8e57-36a00fe39dd9-22963670/cam5"
TEST_9DD9_22963670_CAM6_PATH: "/workspace/duanzx@xiaopeng.com/code/AICT-main/iHarmony4/test/c-f560ab8e-0f35-31fe-8e57-36a00fe39dd9-22963670/cam6"
TEST_9DD9_22963670_CAM7_PATH: "/workspace/duanzx@xiaopeng.com/code/AICT-main/iHarmony4/test/c-f560ab8e-0f35-31fe-8e57-36a00fe39dd9-22963670/cam7"

TEST_7A9F_23012155_CAM0_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-23012155/cam0"
TEST_7A9F_23012155_CAM2_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-23012155/cam2"
TEST_7A9F_23012155_CAM3_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-23012155/cam3"
TEST_7A9F_23012155_CAM4_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-23012155/cam4"
TEST_7A9F_23012155_CAM5_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-23012155/cam5"
TEST_7A9F_23012155_CAM6_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-23012155/cam6"
TEST_7A9F_23012155_CAM7_PATH: "/workspace/duanzx@xiaopeng.com/code/DCCF/assets/c-5b192864-7e2a-3f53-9ac3-79a199e37a9f-23012155/cam7"

IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: "./pretrained_models/hrnet_w18_small_model_v2.pth"
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
