task: m1/c-fff9095c
source_path: /workspace/yangxh7@xiaopeng.com/datasets/xpeng/m1/compare/static_recon/c-fff9095c-176e-3bf0-8479-ddd0c8cf1819
exp_name: runC_2a8
mode: train
loaded_iter: -1
dilate_mask: 40

data:
  split_test: -1
  split_train: 1
  type: Xpeng
  white_background: false
  selected_frames: []  # 110
  cameras: [2]
  extent: 10
  use_colmap: true
  filter_colmap: true
  resolution: 1
  write_obj_bound: false

model:
  gaussian:
    sh_degree: 1
    fourier_dim: 5
    fourier_scale: 1.
    flip_prob: 0.5
    use_tracklets_world: False
  nsg:
    include_bkgd: true
    include_ground: true
    include_obj: true
    include_sky: true
    opt_track: true

train_xpeng:
  iterations_ground: 10000
  iterations_streetgaussian: 40000
  prune_until_iter: 0
  prune_from_iter: 200
  phase2_ground_only_opacity: false

train:
  iterations: 50000
  test_iterations: [5000, 30000, 50000, 80000]
  save_iterations: [5000, 10000, 30000, 50000]
  checkpoint_iterations: [5000, 10000, 30000, 50000]

optim:
  prune_box_interval: 100
  densification_interval: 100
  densify_from_iter: 200
  densify_grad_threshold_bkgd: 0.001
  densify_grad_abs_bkgd: True
  densify_grad_threshold_obj: 0.001
  densify_grad_abs_obj: False
  densify_grad_threshold: 0.001
  densify_until_iter: 10000
  feature_lr: 0.0025
  max_screen_size: 20
  min_opacity: 0.005
  min_opacity_bkgd: 0.02
  min_opacity_grd: 0.02
  opacity_lr: 0.05
  opacity_reset_interval: 1000
  percent_big_ws: 0.1
  percent_dense: 0.01
  position_lr_delay_mult: 0.01
  position_lr_final: 1.6e-06
  position_lr_init: 0.00016
  position_lr_max_steps: 10000
  rotation_lr: 0.001
  scaling_lr: 0.005
  semantic_lr: 0.01

  lambda_dssim: 0.2
  lambda_sky: 0.05
  lambda_ground_acc: 1.
  lambda_ground_rgb: 1.
  lambda_background_on_ground_penalty: 1.
  lambda_sky_scale: []
  lambda_mask: 0.1
  lambda_reg: 0.1
  lambda_depth_lidar: 0.1
  lambda_ground_flatten: 1000.
  lambda_ground_symmetry: 10000.
  lambda_ground_flatten_phase2: 1000.
  lambda_ground_symmetry_phase2: 10000.

  track_position_lr_delay_mult: 0.01
  track_position_lr_init: 0.005
  track_position_lr_final: 5.0e-5
  track_position_max_steps: 30000

  track_rotation_lr_delay_mult: 0.01
  track_rotation_lr_init: 0.001
  track_rotation_lr_final: 1.0e-5
  track_rotation_max_steps: 30000

render:
  fps: 10
  save_image: false
  save_video: true
  save_video_merged: true
  concat_cameras: []
