data:
  cameras:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  extent: 10
  filter_colmap: true
  frame_stride: 1
  input_ground_downsample: 0.02
  resolution: 1
  save_log_images: true
  selected_frames: []
  split_test: -1
  split_train: 1
  type: Xpeng
  use_cam2_extended_l1mask:
  - 720
  - 200
  use_colmap: true
  use_lidar_normal: false
  use_lidar_slice_depth: false
  use_surfel: true
  white_background: false
  write_obj_bound: false
dilate_mask: 40
exp_name: runK_38a
loaded_iter: -1
mode: train
model:
  gaussian:
    flip_prob: 0.5
    fourier_dim: 5
    fourier_scale: 1.0
    sh_degree: 1
    use_tracklets_world: false
  nsg:
    include_bkgd: true
    include_ground: true
    include_obj: false
    include_quasi_static_obj: true
    include_sky: true
    opt_track: true
optim:
  densification_interval: 100
  densify_from_iter: 1500
  densify_grad_abs_bkgd: true
  densify_grad_abs_obj: false
  densify_grad_threshold: 0.0002
  densify_grad_threshold_bkgd: 0.0006
  densify_grad_threshold_obj: 0.0002
  densify_until_iter: 21000
  feature_lr: 0.0025
  lambda_background_init_lidar_constraint:
  - 0.2
  - 25
  - 3.0
  - 70000
  - 75000
  lambda_background_maxscale:
  - 100.0
  - 2.0
  lambda_background_on_ground_penalty: 0.0
  lambda_depth_lidar: 0.1
  lambda_depth_weight_sigma: 0.1
  lambda_dssim: 0.8
  lambda_ground_acc: 1.0
  lambda_ground_flatten: 1000.0
  lambda_ground_flatten_phase2: 0.0
  lambda_ground_symmetry: 10000.0
  lambda_ground_symmetry_phase2: 0.0
  lambda_l1: 0.5
  lambda_mask: 0.1
  lambda_novel_ground_acc: 10.0
  lambda_object_maxscale:
  - 0.0
  - 0.2
  lambda_reg: 0.1
  lambda_sky: 0.05
  lambda_sky_scale: []
  max_screen_size: 250
  min_opacity: 0.005
  min_opacity_bkgd: 0.02
  min_opacity_grd: 0.02
  opacity_lr: 0.05
  opacity_reset_interval: 3000
  percent_big_ws: 0.1
  percent_dense: 0.01
  position_lr_delay_mult: 0.01
  position_lr_final: 1.6e-05
  position_lr_final_obj: 1.6e-06
  position_lr_init: 0.00016
  position_lr_init_obj: 0.00016
  position_lr_max_steps: 26000
  prune_after_densify: true
  prune_box_interval: 100
  rotation_lr: 0.001
  scaling_lr: 0.005
  scaling_lr_final: 0.001
  semantic_lr: 0.01
  track_position_lr_delay_mult: 0.01
  track_position_lr_final: 5.0e-05
  track_position_lr_init: 0.005
  track_position_max_steps: 26000
  track_rotation_lr_delay_mult: 0.01
  track_rotation_lr_final: 1.0e-05
  track_rotation_lr_init: 0.001
  track_rotation_max_steps: 26000
render:
  concat_cameras: []
  fps: 10
  save_image: false
  save_video: true
  save_video_merged: true
source_path: /workspace/group_share/adc-sim/users/yangxh7/datasets/fm_pose_crop/c-078f16e4-274f-37a2-97f5-9afe6aa542ed
task: m1/fm_fixed/c-078f16e4
train:
  checkpoint_iterations:
  - 31500
  iterations: 31500
  save_iterations:
  - 31500
  test_iterations:
  - 31500
train_xpeng:
  iterations_ground: 10500
  iterations_streetgaussian: 31500
  phase1_exclude_obj_bound: true
  phase1_only_cam2: false
  phase1_save: false
  phase2_ground_only_opacity: true
  phase2_include_obj_bound: true
  phase2_no_ground: false
  prune_from_iter: 2000
  prune_until_iter: 10500
