XData:
  config:
    allow_use_cache_only: false
    data_cache: /dataset_perf1/simulation
    data_dir: /dataset/downloader_v2/repository
    gxodips_id: zg
base_dir: "placeholder, should updated when run"
batch_size: 4
bev_resolution: 0.1
cam_list:
- cam0
- cam2
- cam3
- cam4
- cam5
- cam6
- cam7
center_point:
  x: 0.0
  y: 0.0
check_calibration: true
clip_list:
- "placeholder, should updated when run"
cliprun_id: "placeholder, should updated when run"
colmap_config:
  fusion_num_consistent: 4
  fusion_num_neighbors: 50
  fusion_type: sweep
  image_undistored_with_cuda: false
  num_patch_match_src_images: 8
  patch_match_stereo_type: sweep
  ceres_dense_backend_type: LAPACK
  ceres_sparse_backend_type: SUITE_SPARSE
  max_num_images_direct_sparse_solver: 50000
colmap_ref_cam: cam0
cross_trip_image_match_model: roma
cut_range: 20
datarun_id: "placeholder, should updated when run"
dataset_name: "placeholder, should updated when run"
depth_loss_weight: 100
dump_clip_data: true
dump_data_threads: 8
epochs: 9
est_plane_use_adaptive_offset: true
eval: false
exp_dir: "placeholder, should updated when run"
extrinsic:
  rotation_deg: 0.5
  start_epoch: 0
  translation_m: 0.5
image_height: 800
image_width: 800
ips: true
laplacian_loss_weight: 1
lidar_list: []
lr:
  vertices_label: 0.1
  vertices_rgb: 0.1
  vertices_z: 0.001
lr_gamma: 0.1
lr_milestones:
- 1
- 7
max_angle_diff_thr: 10.0
merge_success_ratio_thre: 0.5
min_distance: 0.2
mode: recon
normal_loss_weight: 0
num_workers: 4
pos_enc: 5
pose_source: colmap
rand_seed: 17
record_type: SENSOR_CLIP_RECORD_TYPE
ref_cam: cam2
replace_name: false
replace_translation_calibration: true
rigid_ba: true
rome_cam_list_mode: 3
scene: parking
seg_loss_weight: 1
single_sfm_success_ratio_thre: 0.75
single_sfm_threads: 2
slice_angle_diff_threshold: 2.0
slice_distance_diff_threshold: 0.5
sql_filter: "placeholder, should updated when run"
use_mvs_supervise: true
version: 1.4
rome_output_dir: "placeholder, should updated when run"
trips_json: "placeholder, should updated when run"
pretrained_model_path: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models
superpoint_model_path: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models/superpoint_v1.pth
superglue_model_path: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models/superglue_outdoor.pth
netvlad_model_path: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models/VGG16-NetVLAD-Pitts30K.mat
dino_salad_model_path: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models/salad/dino_salad.ckpt
mask2former_single_gpu: true
mask2former_deuque_limit: 10
mask2former_batch_size: 1
mask2former_model_path: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models/mask2former_mapillary_vistas_swin_L.pkl
code_dir: /surface_reconstruction
mask2former_cfg_path: /surface_reconstruction/Mask2Former/maskformer2_swin_large_IN21k_384_bs16_300k.yaml
vehicle_calibration_path: /surface_reconstruction/configs/vehicle.yaml
log_multi_trip: true
image_match_model: light_glue
light_glue_weights: /workspace/group_share/adc-sim/users/zf/recon_pretrained_models/superpoint_lightglue_v0-1_arxiv.pth
adaptive_batch_size: false
sp_batch_size: 6
sp_workers: 4
colmap_path: /tmp/colmap/build/src/colmap/exe/colmap
retrieval_diff_cam_score_thre: 0.5
retrieval_same_cam_score_thre: 0.5
retrieval_pair_max_dist: 20
retrieval_nms_range: 5
retrieval_min_bev_overlap_area: 10
retrieval_max_pair_per_trip: 100
retrieval_pair_downsample_distance: 1.0
retrieval_skip_min_num: 3
min_roma_match_certainty: 0.2
image_retrival_cfg:
  use_augmented_image_retrival: false
  augmented_cam_id: 2
  augmented_type_num: 3
  score_increase_gap: 0.15
  readjust_score: 0.51
roma_min_cerntainty: 0.2
only_save_final_epoch_result: true
save_rendered_image: false
grid_guassian_smoothing: true
draw_cam_traj_on_bev_image: false
training_crop_image_by_label: true
use_auto_cut_center: true
cutoff_radius: 500.0
rome_downsample_distance_threshold: 0.0
rome_downsample_angle_threshold: 0.0
extrinsic_slice_interval: 30
mesh_z_scale: 1.0
reuse_mesh_prior_z: true
log_every_n_steps: 10
est_plane_fixed_offset: 0.8
est_plane_adaptive_offset_ratio: 0.05
flatten_bev_curb_depth: true
use_avm_cam: false
gpu_per_node: 1
world_size: 1
recon_for_mvsnet: true
bev_resolution_for_parking: 0.02
avm_cam_list: []
run_mvs: false
