version: 1.4
mode: recon
ips: false
dump_data_threads: 64
single_sfm_threads: 16

base_dir: /workspace/yuhangl@xiaopeng.com/exp_reconstruction/test_data
exp_dir: /workspace/yuhangl@xiaopeng.com/exp_reconstruction/test_0303

dataset_name: vision_bases_gt
record_type: POI_SUBRUN_RECORD_TYPE
data_cache_saving_dir: /workspace/group_share/adc-perception-staticxnet/mapless_warmup_cache
sql_filter : id like '6167f785529d2e2bf2b7db06'
clip_list:
- c-4b185f4c-7c41-3d41-9de0-114d16004ade
- c-2ac5ac09-a6d7-3fc1-a532-2f4f345bbb88
- c-757eca10-7960-3515-b0c6-d1dd720ddecc
- c-7138327e-2fbc-3638-b0a9-89f1186f2a7a
- c-89a647e4-11ae-320b-adeb-f859326ce3e5
- c-99aa0f0d-f7c4-30bc-92b7-3936e6968b00
- c-f5c4e97b-cac3-3ead-a117-4d5e0bb72487
- c-c97f36dd-d993-309a-9482-2d6389f7f988
- c-cc54f989-af82-3efc-ba2c-b903a03e30af
- c-6a58f3ac-d7ff-3536-94b7-fe0d4cf0a8dd
- c-ffadf84d-b454-3079-9364-afc2f8f419ec
- c-6a8f761c-a7bd-3451-ae0a-fa82f3d873c0
- c-e6a2030a-553a-3d8f-a42c-3a51923a8835
- c-0fe68a44-6056-3202-bbf7-268e78b081cb
- c-333dba5f-08f1-3011-896a-876a45743806

XData:
  config: {'data_dir': "/dataset/downloader_v2/repository",
            'data_cache': "/dataset_perf0",
            'allow_use_cache_only': false}

slice_angle_diff_threshold: 2.0
slice_distance_diff_threshold: 1.0
single_sfm_success_ratio_thre: 0.75
merge_success_ratio_thre: 0.5

batch_size: 4
bev_resolution: 0.1
use_mvs_supervise: true
replace_translation_calibration: true
check_calibration: true
max_angle_diff_thr: 10.0

lidar_list: []
cam_list:
- cam0
- cam2
- cam3
- cam4
- cam5
- cam6
- cam7
center_point:
  x: 0.0
  y: 0.0
colmap_ref_cam: cam0
cut_range: 20
epochs: 9
eval: false
extrinsic:
  rotation_deg: 0.5
  start_epoch: 0
  translation_m: 0.5
image_height: 800
image_width: 800
laplacian_loss_weight: 1
lr:
  rotations: 0.01
  translations: 0.01
  vertices_label: 0.1
  vertices_rgb: 0.1
  vertices_z: 0.001
lr_gamma: 0.1
lr_milestones:
- 1
- 7
min_distance: 0.2
normal_loss_weight: 0
num_workers: 4
pos_enc: 5
pose_source: colmap
rand_seed: 17
ref_cam: cam2
replace_name: false
rigid_ba: true
seg_loss_weight: 1
depth_loss_weight: 100
colmap_config:
  image_undistored_with_cuda: false # [false(default), true]
  patch_match_stereo_type: "sweep" # [sweep(default), ACMH]
  num_patch_match_src_images: 8 # default=8
  fusion_type: "sweep" # [sweep(default), ACMH]
  fusion_num_consistent: 4 # [default=4]
  fusion_num_neighbors: 50 # [default=50]
cross_trip_image_match_model: roma
est_plane_use_adaptive_offset: True
rome_cam_list_mode: 3