include_configs:
  - ../train/gsm/gsm.yaml
  - ../train/gsm/backbone_pure_unet.yaml
  - dataset.yaml

accumulate_grad_batches: 1

# data loader
duplicate_num: 1
batch_size: 1
test_set_shuffle: false
keep_surface_voxels: false

# encoder module
encoder:
  resize_projection_input: false
  encoder_modules: ['conv']

  # conv encoder for image
  conv_params:
    n_filter_list: [3, 16, 32, 32]
    n_stride_list: [1, 1, 2]
    n_kernel_list: [3, 3, 3]
    n_padding_list: [1, 1, 1]
    n_residual_list: [false, true, true]
    n_use_gn_list: [false, false, false]
    conv_encoder_out_dim: 32

# sky module
use_skybox: true
skybox_target: 'panorama_full'
skybox_net: 'identity'
skybox_feature_source: 'conv'
skybox_resolution: 512
skybox_forward_sky_only: true # ! forward the whole image
model_midground: false

# renderer
renderer:
  target: 'FeatureRenderer'
  decoder_for_sky_only: true # ! do not decode the foreground (that is from 3DGS)
  head:
    target: 'ResConvHead'
    params:
      n_residual_block: [true, true, false]
      n_filter_list: [32, 16, 16, 3]
      n_upsample_list: [false, false, false]
      n_downsample_list: [false, false, false]

rasterizing_downsample: 2 # saying to original resolution

# loss
log_gaussian_stats: true
only_sup_foreground: false # ! foreground and background together
render_target_is_object: false

# overwrite ../train/gsm/backbone_pure_unet.yaml
backbone:
  params:
    lifter_params:
      img_feature_source: conv
      img_in_dim: 32
      voxel_out_dim: 32

    img_feature_source: conv
    in_channels: 32
    num_blocks: 3
    f_maps: 32
    f_maps_2d: 32
    neck_dense_type: "UNCHANGED"
    neck_bound: [128, 128, 32] # ! useless
    use_attention: false
    gs_enhanced: "original"
    gs_free_space: ${gs_free_space}
    gsplat_upsample: 3
    occ_upsample: 2 # subdivide 2x2x2
    max_scaling: 0.5
    max_return: 2
    feature_pooling_2d: "max"


render_weight: 1.0
alpha_weight: 1
perceptual_weight: 0.5
perceptual_start_epoch: 1
use_ssim_loss: true
perceputal_resize_height: 464
supervise_image_resize: [464, 960]

model: gsm
